### PR TITLE
Fixes from API review:

### LINKED ISSUE #1275: Review nullability of all reference type occurrences in the API
(We may want tooling to make this simpler, e.g. listing all methods/properties which mention any reference types anywhere.)

### PR DESCRIPTION
**Pull request by jskeet**
- Equals(object) should accept null
- (Implementation detail) use pattern matching in Equals
- Add documentation for ParseResult.ConvertTo type parameter
- Improve formatting of documentation for ZoneLocalMapping (docfx bug?)

Fixes #1275

### CODE REVIEW

File: src/NodaTime/LocalInstant.cs [hunk 1]
```diff
@@ -187,7 +187,7 @@ internal Instant SafeMinus(Offset offset)
         /// <c>true</c> if the specified <see cref="System.Object"/> is equal to this instance;
         /// otherwise, <c>false</c>.
         /// </returns>
-        public override bool Equals(object obj) => obj is LocalInstant && Equals((LocalInstant)obj);
+        public override bool Equals(object? obj) => obj is LocalInstant other && Equals(other);
```
Comment (malcolmr) [inline src/NodaTime/LocalInstant.cs]: Not that it matters too much, but we seem to be writing `Equals(object?)` three different ways:

`=> obj is LocalInstant other && Equals(other);`
`=> obj is LocalInstant other && this == other;`
`=> Equals(obj as LocalInstant)`

Is there any reason to prefer one over the others? If not, can we at least make them consistent?

Comment (jskeet) [reply src/NodaTime/LocalInstant.cs]: The first is the most common one for value types.

The second is a very slight (perhaps negligible) optimization if I happen to spot that `Equals` calls `==` directly.

The third is the simplest way of doing the first but for reference types.

So I don't mind 1 and 3 existing. Perhaps we should standardize between 1 and 2 though.
